# Azure infrastructure
. $PSScriptRoot/scripts/ConvertTo-Hashtable.ps1

$ENV_AZURE_ENV_NAME = $env:ENV_AZURE_ENV_NAME
$ENV_AZURE_DEPLOY_LOCATION = $env:ENV_AZURE_DEPLOY_LOCATION
$ENV_AZURE_DEPLOY_TENANT_ID = $env:ENV_AZURE_DEPLOY_TENANT_ID
$ENV_AZURE_DEPLOY_APP_CLIENT_ID = $env:ENV_AZURE_DEPLOY_APP_CLIENT_ID
$ENV_AZURE_DEPLOY_APP_CLIENT_SECRET = $env:ENV_AZURE_DEPLOY_APP_CLIENT_SECRET
$ENV_AZURE_DEPLOY_SUBSCRIPTION_ID = $env:ENV_AZURE_DEPLOY_SUBSCRIPTION_ID
$ENV_AZURE_DEPLOY_STACK_ENV_NAME = "docusaurops-$ENV_AZURE_ENV_NAME"
$ENV_AZURE_DEPLOY_RESOURCE_PREFIX = "docusaurops"
$ENV_AZURE_DEPLOY_STACK_RBAC_PRINCIPALS = $env:ENV_AZURE_DEPLOY_STACK_RBAC_PRINCIPALS ? (@($env:ENV_AZURE_DEPLOY_STACK_RBAC_PRINCIPALS | ConvertFrom-Json) | ConvertTo-Hashtable) : $null
$ENV_AZURE_DOCUSAUROPS_ENTRA_ID_CLIENT_ID = $env:ENV_AZURE_DOCUSAUROPS_ENTRA_ID_CLIENT_ID
$ENV_AZURE_DOCUSAUROPS_ENTRA_ID_CLIENT_SECRET = $env:ENV_AZURE_DOCUSAUROPS_ENTRA_ID_CLIENT_SECRET
$ENV_AZURE_DEPLOY_STACK_RG_NAME = "rg-$ENV_AZURE_DEPLOY_STACK_ENV_NAME"
$ENV_AZURE_DOCUSAUROPS_CERT_PASSWORD = $env:ENV_AZURE_DOCUSAUROPS_CERT_PASSWORD
$ENV_AZURE_DOCUSAUROPS_CERT_BASE64_PFX = $env:ENV_AZURE_DOCUSAUROPS_CERT_BASE64_PFX
$ENV_AZURE_DOCUSAUROPS_DOMAIN = "$ENV_AZURE_DEPLOY_RESOURCE_PREFIX-$ENV_AZURE_ENV_NAME.$ENV_AZURE_DEPLOY_LOCATION.cloudapp.azure.com" # Only works in DEV for demo purpose, in PROD you should use a custom domain with a valid certificate
$ENV_AZURE_DOCUSAUROPS_ROOT_WEBAPP_NAME = $env:ENV_AZURE_DOCUSAUROPS_ROOT_WEBAPP_NAME

# Required by deploy-site and documentation build flows in CI.
$ENV_AZURE_DOCUSAUROPS_SITE_URL = $env:ENV_AZURE_DOCUSAUROPS_SITE_URL